#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         3
bspc config border-radius 	10
bspc config window_gap          12
bspc config top_padding		50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a alacritty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a galculator state=floating
bspc rule -a thunar state=floating

# Border
bspc config focused_border_color        "#8da101"
bspc config normal_border_color         "#5c6a72"
bspc config active_border_color         "#5c6a72"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill ~/.config/bspwm/assets/wallpaper_3840x2160.png &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &
# Automatically lock after some time
xss-lock --transfer-sleep-lock -- i3lock -i ~/.config/bspwm/assets/wallpaper_1920x1080.png &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
