export ZSH="$HOME/.config/zsh/.oh-my-zsh"

ZSH_THEME="nanotech"
plugins=(git)

DISABLE_AUTO_TITLE="true"

source $ZSH/oh-my-zsh.sh

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(direnv hook zsh)"

export CPATH="${CPATH}:/opt/homebrew/include:/opt/homebrew/lib"

alias vim="nvim"
