# everyday
cask "alacritty"
cask "cyberduck"
cask "discord"
cask "disk-inventory-x"
cask "gimp"
cask "keepassxc"
cask "librewolf"
cask "spotify"
cask "steam"
cask "transmission"
cask "runelite" # :)
cask "jellyfin-media-player"

# LaTeX / Markdown
cask "mactex-no-gui"
brew "marked"
cask "skim"

# office
cask "microsoft-word"
cask "microsoft-powerpoint"
cask "microsoft-excel"
cask "microsoft-teams"

# other formulae
brew "gnuplot"
brew "python@3.11"
brew "btop"
brew "neofetch"

# neovim stuff
brew "neovim"
brew "yarn"
brew "node"
brew "ripgrep"
brew "fd"
