# everyday
cask "alacritty"
cask "discord"
cask "disk-inventory-x"
cask "keepassxc"
cask "darktable"
cask "librewolf"
cask "spotify"
cask "steam"
cask "transmission"
cask "jellyfin-media-player"
cask "hex-fiend"
cask "vlc"

# LaTeX
cask "mactex-no-gui"
cask "skim"

# office
cask "microsoft-word"
cask "microsoft-powerpoint"
cask "microsoft-excel"
cask "microsoft-teams"

# formulae
brew "gnuplot"
brew "btop"
brew "neofetch"

# neovim stuff
brew "neovim"
brew "yarn"
brew "node"
brew "ripgrep"
brew "fd"
