
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#d8d3ba"
yellow = "#dfa000"

[colors.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#d8d3ba"
yellow = "#dfa000"

[colors.primary]
background = "#f3ead3"
foreground = "#5c6a72"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[[keyboard.bindings]]
chars = "{"
key = "LBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "}"
key = "RBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Semicolon"
mods = "Alt"

[[keyboard.bindings]]
chars = "~"
key = "Key5"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
title = "Terminal"

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
