#! /bin/bash

# Menu Bar Update
get_date(){
	echo -e "$(date +"%a %d, %H:%M")"
}

get_cpu(){
	read cpu a b c previdle rest < /proc/stat
	prevtotal=$((a+b+c+previdle))
	sleep 0.5
	read cpu a b c idle rest < /proc/stat
	total=$((a+b+c+idle))

	cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
	echo -e "$cpu% CPU"
}

get_mem(){
	mem=$(free -m | awk 'NR==2{printf "%.2f\n", $3*100/$2 }')
	echo -e "$mem% RAM"
}

get_bat(){
	charge=$(cat "/sys/class/power_supply/BAT0/capacity")
	charging=$(cat "/sys/class/power_supply/BAT0/status")

	status=""
	if [ $charging == "Charging" ]; then
		status="*"
	fi
	echo -e "$status$charge% POW"
}

get_vol(){
	status=$(amixer -c 1 get Master | grep 'Mono:' | awk '{print $6}' | sed 's/^.//;s/.$//')
	volume=$(amixer -c 1 get Master | grep 'Mono:' | awk '{print $4}' | sed 's/^.//;s/.$//')
	if [ $status == "off" ]; then
		volume=""
	else status=""
	fi
	echo -e "$volume$status VOL"
}


# Main Loop
while true; do
	xsetroot -name "  $(get_mem) | $(get_cpu) | $(get_bat) | $(get_vol) | $(get_date)  "
	sleep 5s
done &
